# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bebatut.fr
title: Bérénice Batut
subtitle: test
email: berenice.batut@gmail.com
author: Bérénice Batut
description: > # "Website description"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/bebatut
  - title: github
    url: https://github.com/bebatut
  - title: linkedin
    url: https:/fr.linkedin.com/in/berenicebatut
  - title: flickr
    url: https://www.flickr.com/photos/134305289@N03

sites:
  - title: Research
    type: research
    url: https://research.bebatut.fr
  - title: Blog
    type: blog
    url: https://blog.bebatut.fr
  - title: DIY
    type: diy
    url:
  - title: Photos
    type: photos
    url: https://www.flickr.com/photos/134305289@N03