# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bebatut.fr
title: Bérénice Batut
subtitle: test
email: berenice.batut@gmail.com
author: Bérénice Batut
description: > # "Website description"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Twitter
    type: twitter
    url: https://twitter.com/bebatut
  - title: Github
    type: github
    url: https://github.com/bebatut
  - title: Linkedin
    type: linkedin
    url: https:/fr.linkedin.com/in/berenicebatut
  - title: Flickr
    type: flickr
    url: https://www.flickr.com/photos/134305289@N03

sites:
  - title: Research
    type: research
    url: https://research.bebatut.fr
  - title: Photos
    type: photos
    url: https://www.flickr.com/photos/134305289@N03